# Generated by Django 4.0.2 on 2022-02-21 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('country_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
